# Generated by Django 5.1.5 on 2025-03-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('current_class', models.CharField(choices=[('Play Group', 'Play Group'), ('Pre Primary 1', 'Pre Primary 1'), ('Pre Primary 2', 'Pre Primary 2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50)),
                ('religion', models.CharField(choices=[('Christian', 'Christian'), ('Muslim', 'Muslim'), ('Other', 'Other')], max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('prev_school', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('id_no', models.CharField(max_length=20)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian')], max_length=20)),
                ('contact_1', models.CharField(max_length=10)),
                ('contact_2', models.CharField(max_length=10)),
                ('res_address', models.CharField(max_length=50)),
                ('associate', models.CharField(max_length=100)),
                ('ass_contact', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
